version: 0.0
os: linux

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
files:
  - source: /
    destination: /home/ec2-user/back
    overwrite: yes
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
